import {
  Moon,
  SunMedium,
  PartyPopper,
  List,
  House,
  User,
  Plus,
  Copy,
  Images,
  ChevronLeft,
  MessageCircleQuestion,
  Shapes,
  Info,
  Stars,
  X,
  Award,
  Gamepad,
  Trophy,
} from "lucide-react-native";

export const Icons = {
  sun: SunMedium,
  list: List,
  info: Info,
  trophy: Trophy,
  home: House,
  images: Images,
  copy: Copy,
  plus: Plus,
  category: Shapes,
  profile: User,
  award: Award,
  cross: X,
  gamepad: Gamepad,
  star: Stars,
  question: MessageCircleQuestion,
  logo: PartyPopper,
  arrowLeft: ChevronLeft,
  moon: Moon,
} as const;

export type IconNames = keyof typeof Icons;
